foo/config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  get :my_stat_test, to: 'pages#my_stat_test'
  get :other_stat_test, to: 'pages#other_stat_test'
  resources :campaigns, only: [:index]
  devise_for :consumers, controllers: { omniauth_callbacks: 'consumers/omniauth_callbacks' }, skip: [:registrations]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  #
  resources :identities, only: [:show], param: :user_name
  resources :pages do
    collection do
      get :profile
    end
  end
end

foo/app/models/campaign.rb
class Campaign < ApplicationRecord
  HASHTAG_REGEX = /\A#[a-zA-Z0-9]+\z/
  validates :brand_name, presence: true
  validates :hashtag, presence: true, format: { with: Campaign::HASHTAG_REGEX }
  validates :starts_on, presence: true
  validates :stops_on, presence: true
  validates :banner_picture_url, presence: true
  enum state: { in_definition: 0, ongoing: 1, completed: 2 }
end

foo/app/controllers/campaigns_controller.rb
class CampaignsController < ApplicationController
  def index
    @campaigns = Campaign.all.select { |c| c.ongoing? }.sort_by{ |c| c.stops_on }.reverse
  end
end

foo/app/views/campaigns/index.html.erb
<%= c 'header' %>
<%= c 'wrapper' do %>
  <%= c 'side' do %>
    <%= c 'username', user_name: current_consumer.instagram.user_name, picture_url: current_consumer.instagram.profile_pict %>
    <%= c 'bio', user: current_consumer %>
    <%= c 'button', additionnal_classes: "secondary" do %>
      > My Instagram Report
    <% end %>
    <%= c 'community' %>


  <% end %>
  <%= c 'main' do %>
    <%= c 'feed' do %>
      <% @campaigns.each do |campaign| %>
        <%= c 'campaign', campaign: campaign %>
      <% end %>
    <% end %>
  <% end %>
<% end %>